on:
  push:
    branches:
      - main
name: Publish on Netlify

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build && yarn export

      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=dist --prod --message "$GITHUB_SHA"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
